<%

if ENV['RAILS_ENV'] =='production'
  neo4j_url = ''
else
  neo4j_url = 'http://localhost:7475'
end
%>

production: &base
  neo4j:
    url: <%=neo4j_url%>

development:
  <<: *base
  neo4j:
    url: <%=neo4j_url%>

test:
  <<: *base
  neo4j:
    url: <% if ENV['CI'] %>'http://10.255.12.155:7476'<% else %>'http://localhost:7476'<% end %>
