<%

if ENV['RAILS_ENV'] =='production'
  neo4j_url = 'http://localhost:7474'
else
  neo4j_url = 'http://localhost:7474'
end
%>

production: &base
  neo4j:
    url: <%=neo4j_url%>

development:
  <<: *base
  neo4j:
    url: <%=neo4j_url%>

test:
  <<: *base
  neo4j:
    url: 'http://localhost:7475'
